### ISSUE TITLE
The ffdhe groups are not curves

### ISSUE THREAD

**Issue by daira** [syncsynchalt/illustrated-tls13#10]
The description of the supported groups extension describes it as having 10 curves, but the ffdhe entries are not elliptic curves (they are finite fields). That is, this extension really does in practice refer to groups and not just curves.

**Comment by syncsynchalt** [comment]
Hi Daira! Sorry for the delay in getting to this, I've been out in the desert getting away from it all.

Thanks for noticing this and opening an issue. I wasn't familiar with FFDHE (or rather, didn't realize it is just DHE). I've read up on the history and context of the "Supported Groups" (née "Supported Curves") extension and think I have enough to fix the wording on that section.

Here's my first pass at better wording, let me know what's not quite right and I'll keep amending:

> The client has indicated that it supports key exchange using ten
> methods: five using elliptic curves (EC) and five using finite
> fields.
>
> This extension was formerly called "Supported Curves" and in 
> earlier versions of TLS only indicated elliptic curves. It 
> was renamed and repurposed in TLS 1.3 to include indicating
> support for non-EC key exchange.

Here's what I dug up in the TLS WG list around the rename, I'm putting it here for my own reference when/if I need to find it again. It's not directly related to the wording change.

* [TLS 1.3 RFC author explicitly combining "supported (FF) groups" extension with existing "supported curves" extension](https://mailarchive.ietf.org/arch/msg/tls/_f-nBjvK3SUybLuD3iTm8SWGp3M/)
* [Thread a month later, around explicitly amending RFC4492 to note curves -> groups, though the amendment never occurred afaict](https://mailarchive.ietf.org/arch/msg/tls/MNbR83lvMFkGyjC_cCWAMKjwBjE/)
* [Thread around finalizing the merge/rename, in what became RFC7919, half a year later](https://mailarchive.ietf.org/arch/msg/tls/qa74dNKesSoQ0asQQI06pZ5IOPY/)

**Comment by syncsynchalt** [comment]
(dumping some thoughts here as I think about tweaking things further)

I try to pitch this project at the level of being a teaching tool, and I'd like to hint to readers a few things:

- ECDHE is the "intended" key exchange method, at least at time of creation of TLS 1.3
- (FF)DHE is still supported, but is currently not considered as strong as ECDHE, and is (as I understand it) used by clients stuck on older crypto libraries / hardware

But I want to future proof things too:

- ECDHE might be broken, and we might fall back on FFDHE
- PQC will add new KEX methods, which may or may not be included in this extension
   - the PQC drafts have probably already established this, but I haven't read them yet 😳 
   
None of the above bullets are covered by the new wording, but if you have thoughts let me know!

**Comment by syncsynchalt** [comment]
Closing issue as I think the major problem is resolved. Thanks again!
